export const homeData = [
  {
    id: 1,
    name: "Top Gun",
    rating: 8.3,
    time: "2hr : 10mins",
    desc: "After thirty years, TOP GUN's elite graduates on a mission that demands the ultimate sacrifice from those chosen to fly it.",
    starring: "Tom Cruise, Jennifer Connelly, Miles Teller",
    genres: "Action",
    tags: "Action, Drama",
    cover: "../images/home1.jpg",
    video: "../video/video1.mp4",
    date: "20-Jan-2022",
  },
  {
    id: 2,
    name: "John Wick 4",
    rating: 8.0,
    time: "2hr : 22mins",
    desc: "John Wick uncovers a path to defeating The High Table. Wick must face off against a new enemy with powerful alliances across the globe.",
    starring: "Keanu Reeves, Laurence Fishburne, George Georgiou",
    genres: "Action",
    tags: "Action, Crime, Thriller",
    cover: "../images/home2.jpg",
    video: "https://www.imdb.com/video/vi289916185/?playlistId=tt10366206&ref_=tt_ov_vi",
    date: "10-JUL-2022",
  },
  {
    id: 3,
    name: "Red Notice",
    rating: 6.3,
    time: "2hr : 22mins",
    desc: "Piracy is an act of robbery or criminal violence by ship or boat-borne attackers upon another ship or a coastal area, typically with the goal of stealing cargo and other valuable items or properties. ",
    starring: "Dwayne Johnson, Ryan Reynolds,Gal Gadot",
    genres: "Action",
    tags: "Adventures,Action ",
    cover: "../images/home3.jpg",
    video: "../video/video3.mp4",
    date: "20-FEB-2022",
  },
  {
    id: 4,
    name: "The Adam Project",
    rating: 6.7,
    time: "2hr : 22mins",
    desc: "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self for a mission to save the future.",
    starring: "Ryan Reynolds, Walker Scobell",
    genres: "Action",
    tags: "Action, Adventures",
    cover: "../images/home4.jpg",
    video: "https://www.imdb.com/video/vi289916185/?playlistId=tt10366206&ref_=tt_ov_vi",
    date: "12-Aug-2022",
  },
  
]
export const upcome = [
  {
    id: 1,
    cover: "../images/upcome/u1.jpg",
    name: "Fast X",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u2.jpg",
    name: "The Flash",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u3.jpg",
    name: "The Creator",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u4.jpg",
    name: "The Marvels",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u5.jpg",
    name: "Meg 2: The Trench",
    time: "2hr : 38mins",
  },
  {
    id: 6,
    cover: "../images/upcome/u6.png",
    name: "The Little Mermaid ",
    time: "2hr : 38mins",
  },
  {
    id: 7,
    cover: "../images/upcome/u11.jpg",
    name: " Wonka",
    time: "2hr : 38mins",
  },
  {
    id: 8,
    cover: "../images/upcome/u9.jpg",
    name: "The Magic Flute ",
    time: "2hr : 38mins",
  },
]
export const latest = [
  {
    id: 1,
    cover: "../images/upcome/u6.png",
    name: "The Little Mermaid ",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/upcome/u11.jpg",
    name: " Wonka",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/upcome/u9.jpg",
    name: "The Magic Flute ",
    time: "2hr : 38mins",
  },
  {
    id: 4,
    cover: "../images/upcome/u8.jpg",
    name: "The Mother ",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/upcome/u7.jpg",
    name: "The Peter Pan ",
    time: "2hr : 38mins",
  },
  {
    id: 6,
    cover: "../images/upcome/u12.jpg",
    name: "Murder Mystery 2 ",
    time: "2hr : 38mins",
  },
  {
    id: 7,
    cover: "../images/upcome/u13.jpg",
    name: "The Strays ",
    time: "2hr : 38mins",
  },
  {
    id: 8,
    cover: "../images/upcome/u15.jpg",
    name: "Your Place or Mine ",
    time: "2hr : 38mins",
  },
  {
    id: 9,
    cover: "../images/upcome/u14.jpg",
    name: "Boston Strangler ",
    time: "2hr : 38mins",
  },
  {
    id: 10,
    cover: "../images/upcome/u16.jpg",
    name: " Blood & Gold",
    time: "2hr : 38mins",
  },
]

export const trending = [
  {
    id: 1,
    name: "Puss in Boots",
    rating: 7.9,
    time: "2hr : 22mins",
    desc: "When Puss in Boots discovers that his passion for adventure has taken its toll and he has burned through eight of his nine lives",
    genres: "Action",
    tags: "Action, Adventures, Animation",
    cover: "../images/img/slide1.png",
    date: "20-Jan-2022",
  },
  {
    id: 2,
    name: "Encanto",
    rating: 7.2,
    time: "2hr : 22mins",
    desc: "A Colombian teenage girl has to face the frustration of being the only member of her family without magical powers ",
    starring: "Brenda Chapman, Jeff Nathanson",
    genres: "Animation",
    tags: "Adventures,Animation,Family",
    cover: "../images/img/slide2.jpg",
    date: "10-JUL-2021",
  },
  {
    id: 3,
    name: "Moana",
    rating: 7.8,
    time: "2hr : 22mins",
    desc: "Moana's island, she answers the Ocean's call to seek out the Demigod to set things right. ",
    starring: "James Chinlund, Jeff Nathanson",
    genres: "Adventures",
    tags: "Adventures,Action ",
    cover: "../images/img/slide3.jpg",
    date: "20-FEB-2010",
  },
]
export const recommended = [
  {
    id: 4,
    cover: "../images/rec/rec1.jpg",
    name: "Shang-Chi",
    time: "2hr : 38mins",
  },
  {
    id: 5,
    cover: "../images/rec/rec2.jpg",
    name: "Death on the Nile",
    time: "2hr : 38mins",
  },
  {
    id: 1,
    cover: "../images/rec/rec3.jpg",
    name: "The Gray Man",
    time: "2hr : 38mins",
  },
  {
    id: 2,
    cover: "../images/rec/rec4.jpg",
    name: "Avatar: The Way Of Water",
    time: "2hr : 38mins",
  },
  {
    id: 3,
    cover: "../images/rec/rec5.jpg",
    name: "The Batman",
    time: "2hr : 38mins",
  },
]